version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ~/data/db:/data/db
    ports:
      - "27017:27017"
    # command: "mongoimport --db retirement --collection funds --file \"server/src/data/mock.json\" --jsonArray"
