version: "3"
services:
  app:
    image: ayovev/retirement-tracking-app
    container_name: app
    ports:
      - 8080
    environment:
      - ALPHAVANTAGE_API_KEY=
      - DATABASE_USER=
      - DATABASE_PASSWORD=
      - TOKEN_SECRET=
    restart: on-failure
