version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./server/src/data:/seed/data
    ports:
      - "27017:27017"

  mongo-seed:
    container_name: mongo-seed
    image: mongo
    links:
      - mongo
    volumes:
      - ./server/src/data:/seed/data
    command: "mongoimport --host mongo --db retirement --collection funds --file \"/seed/data/mock.json\" --jsonArray"
