version: "3"
services:
  app:
    image: ayovev/retirement-tracking-app
    container_name: app
    ports:
      - 8080
    environment:
      - ALPHAVANTAGE_API_KEY=
      - IEX_API_KEY=
      - WORLD_TRADING_DATA_API_KEY=

      - DATABASE_USER=
      - DATABASE_PASSWORD=
      - DATABASE_HOST=
      - DATABASE_NAME=

      - TOKEN_SECRET=
    restart: on-failure
